UPPERCASE_WORDS = [
    ("A", "The first letter of the English alphabet. It is commonly used as an indefinite article in sentences."),
    ("USA", "An abbreviation for the United States of America. Often used to refer to the country in news and articles."),
    ("EU", "Short for the European Union. Used to denote the political and economic union of European countries."),
    ("LIVE", "Describes something happening or being shown in real-time. Used to emphasize the immediacy of events in articles."),
    ("LOVE", "An intense feeling of affection or care. Frequently mentioned in articles discussing relationships and emotions."),
    ("TV", "Short for television. Refers to the electronic device or the broadcasting medium."),
    ("FREE", "Denotes something that is given without charge or cost. Often used to attract attention or promote offers in articles."),
    ("AI", "Abbreviation for Artificial Intelligence. Refers to the simulation of human intelligence in machines."),
    ("API", "Short for Application Programming Interface. Used to define sets of rules and protocols for software applications to interact with each other."),
    ("AM", "Abbreviation for ante meridiem, meaning before noon. Used to denote the morning hours."),
    ("PM", "Abbreviation for post meridiem, meaning after noon. Used to denote the afternoon and evening hours."),
    ("UK", "Abbreviation for the United Kingdom. Refers to the sovereign country consisting of Great Britain and Northern Ireland."),
    ("IQ", "Abbreviation for Intelligence Quotient. Often used in articles related to intelligence and cognitive abilities."),
    ("NYC", "Abbreviation for New York City. Refers to the most populous city in the United States."),
    ("ID", "Short for identification. Used to refer to a document or piece of information that confirms an individual's identity."),
    ("COST", "Refers to the amount of money required to purchase or produce something. Frequently mentioned in articles discussing expenses and pricing."),
    ("DNA", "Abbreviation for Deoxyribonucleic Acid. Refers to the molecule that carries the genetic instructions for the development and functioning of living organisms."),
    ("UPS", "Abbreviation for United Parcel Service. Refers to a global package delivery and supply chain management company."),
    ("IT", "Abbreviation for Information Technology. Used to describe the use, development, and management of computer-based systems."),
    ("ABC", "Can refer to multiple meanings, such as the alphabet or the American Broadcasting Company. Context determines its usage in articles."),
    ("CTO", "Abbreviation for Chief Technology Officer. Denotes a high-level executive responsible for the technological direction of a company."),
    ("ET", "Abbreviation for Eastern Time. Used to refer to the time zone observed in the eastern region of North America."),
    ("HR", "Abbreviation for Human Resources. Often used to describe the department or function responsible for managing personnel within an organization.")

]
